name: Fabletics K8S QA
run-name: Fabletics K8S QA
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-env name=TEST_SECRET::${{ secrets.TEST_SECRET }}"
      - run: echo $TEST_SECRET
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["k8s/deployment/kube.yaml"]'
        env:
          NAMESPACE: spa-qa
      - name: Check the contents
        run: cat "k8s/deployment/kube.yaml"
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "${{ github.workflow }} Started Triggered by ${{ github.actor }} on branch ${{ github.ref_name}}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.workflow }} Started Triggered by ${{ github.actor }} on branch ${{ github.ref_name}}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
