name: K8S QA
run-name: K8S QA

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Create sanitized Subdomain Prefix
        id: subdomain-sanitize
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: "www.remix.com"
          find: '.'
          replace: '-'
      
      - name: Echo the output
        shell: bash 
        run: echo ${{ steps.subdomain-sanitize.outputs.value }}
          
#       - uses: cschleiden/replace-tokens@v1
#         with:
#           files: '["k8s/deployment/kube.yaml"]'
#         env:
#           NAMESPACE: spa-qa
#           SECRET: ${{ env.SECRET }}
          
#       - name: Check the contents
#         run: cat "k8s/deployment/kube.yaml"
        
#       - name: Check Branch Name
#         run: echo ${{ github.event.pull_request.head.ref }}
        
#       - name: Send custom JSON data to Slack workflow
#         id: slack
#         uses: slackapi/slack-github-action@v1.18.0
#         with:
#           # For posting a rich message using Block Kit
#           payload: |
#             {
#               "text": "${{ github.workflow }} Started Triggered by ${{ github.actor }} on branch ${{ github.ref_name}}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
#               "blocks": [
#                 {
#                   "type": "section",
#                   "text": {
#                     "type": "mrkdwn",
#                     "text": "${{ github.workflow }} Started Triggered by ${{ github.actor }} on branch ${{ github.ref_name}}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
#                   }
#                 }
#               ]
#             }
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
